# Autogenerated wrapper script for bat_jll for armv7l-linux-gnueabihf
export bat

JLLWrappers.@generate_wrapper_header("bat")
JLLWrappers.@declare_executable_product(bat)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        bat,
        "bin/bat",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
