# Autogenerated wrapper script for bat_jll for x86_64-w64-mingw32
export bat

JLLWrappers.@generate_wrapper_header("bat")
JLLWrappers.@declare_executable_product(bat)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        bat,
        "bin\\bat.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
